include:
  # Sofle v2.0w
  - board: nice_nano
    shield: sofle_left custom_nice_view_adapter nice_view_gem
  - board: nice_nano
    shield: sofle_right custom_nice_view_adapter nice_view_gem
    # Prospector - Carrefinho
  - board: xiao_ble
    shield: sofle_dongle prospector_adapter

  # Settings reset
  - board: nice_nano
    shield: settings_reset
  - board: xiao_ble
    shield: settings_reset