# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT

# Uncomment the following line to enable the Sofle OLED Display
CONFIG_ZMK_DISPLAY=y

## nice-view-gem
# To enable nice-view-gem support, uncomment the following line
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# nice-view-gem specific configuration
CONFIG_NICE_VIEW_GEM_WPM_FIXED_RANGE=y
CONFIG_NICE_VIEW_GEM_WPM_FIXED_RANGE_MAX=100
CONFIG_NICE_VIEW_GEM_ANIMATION=y
CONFIG_NICE_VIEW_GEM_ANIMATION_MS=960


# Uncomment these two lines to add support for encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
