# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT

# Uncomment the following line to enable the Sofle OLED Display
CONFIG_ZMK_DISPLAY=y

## nice-view-gem
# To enable nice-view-gem support, uncomment the following line
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# nice-view-gem specific configuration
CONFIG_NICE_VIEW_GEM_WPM_FIXED_RANGE=y
CONFIG_NICE_VIEW_GEM_WPM_FIXED_RANGE_MAX=100
CONFIG_NICE_VIEW_GEM_ANIMATION=y
CONFIG_NICE_VIEW_GEM_ANIMATION_MS=960


# Uncomment these two lines to add support for encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y


## Prospector - Carrefinho
# Themes (choose only 1. Comment all for classic theme)
# CONFIG_PROSPECTOR_STATUS_SCREEN_RADII=y
# CONFIG_PROSPECTOR_STATUS_SCREEN_FIELD=y
CONFIG_PROSPECTOR_STATUS_SCREEN_OPERATOR=y

# General settings
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=80
CONFIG_PROSPECTOR_ROTATE_DISPLAY_180=n
CONFIG_PROSPECTOR_LAYER_NAME_UPPERCASE=y

# Modifiers
CONFIG_PROSPECTOR_SHOW_MODIFIERS=y
CONFIG_PROSPECTOR_SHOW_INACTIVE_MODIFIERS=y
CONFIG_PROSPECTOR_MODIFIER_ORDER="GACS"

# Field-specific
CONFIG_PROSPECTOR_ANIMATION_WPM_REFERENCE=70
CONFIG_PROSPECTOR_ANIMATION_INTENSITY_DECAY_SEC=30
CONFIG_PROSPECTOR_ANIMATION_FLOW_DECAY_SEC=300