manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # nice-view-gem
    - name: m165437
      url-base: https://github.com/M165437
    # Prospector - Carrefinho
    - name: carrefinho
      url-base: https://github.com/carrefinho
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # nice-view-gem
    - name: nice-view-gem
      remote: m165437
      revision: main
    # Prospector - Carrefinho
    - name: prospector-zmk-module
      remote: carrefinho
      revision: core/zephyr-4-1
  self:
    path: config
